### PR TITLE
Incorporate feedback from alpha test

### PR DESCRIPTION
**Pull request by fsschneider**
I included most of the feedback that we got from our alpha test.

Still open

- [ ] Write a "Quickstart" (or Getting Started/Introduction) page to the doc. It should explain what `cockpit` is and crucially what the `quantities` are and possibly how the whole thing interacts with `BackPACK`. I only created a placeholder.
- [x] I noticed that the `UpdateSize` quantity is broken. E.g. running example 02 produces update sizes of zero. @f-dangel could you look into this?

What I fixed (or at least partially fixed. @f-dangel could you check them?)

- More prominent `pip install` blocks on the main pages and the examples.
- Fix the bug with the utils files of the examples. They are now expected to be in the same directory and are ignored when testing.
- Added install instructions for both DeepOBS and BackOBS.
- Removed sphinx copybutton (bug with highlighted lines).
- Ignored irrelevant torch warning (now all examples (almost) run without warnings from some external package).
- Added print message when plotting (thus providing more feedback on what the cockpit is currently doing. For the future, we could wrap all these print statements with a togglable option similar to `verbose`.
- First example now shows a blocking plot at the end (is ignored in testing due to proper switching the MPLBACKEND).
- Improved the tick labels for most plots. It is still far from perfect, but it is better.
- Made examples 2-3 more interesting (mostly by letting them run longer).

### CODE REVIEW

**Comment by f-dangel** [comment]
Fixed the bug in `UpdateSize` with #3

**Comment by f-dangel** [comment]
Status (ping @fsschneider):

-   Double-checked installation and examples from a fresh environment
    -   Had to manually install `requests`, it's required in `torchvision` to download data sets, but was somehow not automatically installed in my setting. Nothing we have act on, I think.
    -   Basic and advanced examples work. I also understood how to grab the utility files.

Semi-crucial for the merge/release:

-   DeepOBS example
    -   The `backobs` installation does not work with the latest version of `pip` (21.1). It works with older versions though, but we should update it to work with the latest `pip`. The following works:
        
        ```bash
        pip install 'git+https://github.com/f-dangel/backobs.git@master#egg=backobs'
        ```
    -   I get an `ImportError` when running the script:
        
        ```bash
        File ".../python3.8/site-packages/backobs/utils.py", line 3, in <module>
        from deepobs.pytorch.testproblems import (
        ImportError: cannot import name 'cifar10_vgg16' from 'deepobs.pytorch.testproblems' (.../python3.8/site-packages/deepobs/pytorch/testproblems/__init__.py)
        ```
        
        I guess this is because the installed `DeepOBS` version does not (yet) include the `cifar10_vgg16` problem. We could fix this by installing `DeepOBS` from a later commit.

Further suggested improvements (not crucial for merging/releasing):

-   Basic/Advanced/DeepOBS example: Put reminder to grab the utility files inside a `.. note:` block. In a rush, this may easily be forgotten, so this should be visually more emphasized.
-   Advanced example: Add download link of `02_advanced_fmnist.py` script like in the basic example.
-   Advanced example: The utilities save everything to `../logfiles`. I dropped the files inside my `test` folder, but the results were saved outside, i.e. in `test/../logfiles`, which was a bit annoying, but at least the files are easy to locate because of the messages printed to the terminal. The optimal solution would be to create `logfiles` relative to `02_advanced_fmnist.py`, but I'm not sure how much effort this will take given that the functionality to do so comes from another utility file.
-   DeepOBS example: Add download link of `03_deepobs.py` script like in the basic example.
-   The `pip install ...` statement for Cockpit shows up multiple times. Maybe we can reduce duplication, while keeping the statement easy to spot at a first glance.
-   I like the idea of giving feedback to the user what is happening inside `cockpit` (especially where plots are saved or files are written). Keep in mind thought that enabling `verbose` will provide **very** verbose feedback. For instance, the 2d histogram will be printed to `stdout`. Maybe we can have multiple verbosity levels, but we only need to think about this if users explicitly request this silencing option because they are disturbed/confused/annoyed by `print` messages that show where plots and logs are saved.

File: docs/source/examples/02_advanced_fmnist.rst [hunk 1]
```diff
@@ -5,20 +5,47 @@ Advanced Example
...
+  Step:     2 | Loss: 2.3185
+  Step:     3 | Loss: 2.2932
+  Step:     4 | Loss: 2.2893
+  Step:     5 | Loss: 2.2865
+  Step:     6 | Loss: 2.2780
+  Step:     7 | Loss: 2.2485
+  Step:     8 | Loss: 2.2600
+  Step:     9 | Loss: 2.1823
+  Step:    10 | Loss: 2.0557
+  [cockpit|plot] Saving figure in /home/frank/PhD/Nextcloud/PhD/Projects/2019-10-Cockpit/cockpit/logfiles/cockpit_output__primary10.png
```
Comment (f-dangel) [inline docs/source/examples/02_advanced_fmnist.rst:45]: @fsschneider Maybe you want to replace `/home/frank/PhD/Nextcloud/PhD/Projects/2019-10-Cockpit/` with `~/`

**Review by f-dangel — APPROVED** [review]
